require('ts-node').register({
  project: 'tsconfig-webpack.json',
});

/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit the source file at `./gatsby-config.ts`
 */
module.exports = require('./webpack.dev.config.ts');
