import { WebpackOptions } from 'webpack/declarations/WebpackOptions';

/**
 * @description Webpack Stats Configuration
 * @see https://webpack.js.org/configuration/stats/
 */
export const webpackStatsConf: { [key: string]: WebpackOptions['stats'] } = {
  debug: {
    all: undefined,
    colors: true,
    assets: true,
    assetsSort: 'size',
    children: true,
    chunks: true,
    chunkModules: true,
    chunksSort: 'size',
    entrypoints: true,
    env: true,
    errors: true,
    errorDetails: true,
    modules: true,
    moduleTrace: true,
    performance: true,
    timings: false,
    warnings: true,
    version: false,
    hash: false,
  },
  prod: {
    all: false,
    colors: false,
    assets: false,
    children: false,
    chunks: false,
    chunkModules: false,
    chunkGroups: false,
    chunksSort: 'size',
    entrypoints: false,
    env: true,
    publicPath: false,
    errors: true,
    errorDetails: true,
    modules: false,
    moduleTrace: false,
    performance: true,
    timings: true,
    warnings: true,
    version: false,
    hash: false,
  },
  dev: {
    all: false,
    colors: true,
    assets: false,
    children: false,
    chunks: false,
    chunkModules: false,
    chunkGroups: false,
    chunksSort: 'size',
    entrypoints: false,
    env: true,
    publicPath: false,
    errors: true,
    errorDetails: true,
    modules: false,
    moduleTrace: false,
    performance: true,
    timings: true,
    warnings: true,
    version: false,
    hash: false,
  },
};
