/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, DropShadow, File, Font, Image, Point2D, Typograph } from '@diez/prefabs';

const mirDesignSystemColors = {
  mirLightGreyscaleInverted: Color.rgba(255, 255, 255, 1),
  utilityLightGreyscaleAlmostTransparent: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleGreyLight: Color.rgba(224, 224, 224, 1),
  utilityLightGreyscaleBlack: Color.rgba(43, 43, 43, 1),
  utilityLightGreyscaleAlmostTransparent1: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleGreyMedium: Color.rgba(69, 69, 69, 1),
  utilityLightGreyscaleAlmostTransparent2: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent3: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleGreyMedium1: Color.rgba(69, 69, 69, 1),
  utilityLightGreyscaleTransparent: Color.rgba(255, 255, 255, 1),
  mirLightGreyscale0: Color.rgba(255, 255, 255, 1),
  mirLightAccent1500: Color.rgba(250, 180, 45, 1),
  mirLightPrimary500: Color.rgba(55, 91, 240, 1),
  mirLightPrimary300: Color.rgba(130, 153, 246, 1),
  mirLightPrimary700: Color.rgba(15, 52, 206, 1),
  mirLightGreyscale100: Color.rgba(240, 242, 246, 1),
  mirLightGreyscale200: Color.rgba(232, 236, 242, 1),
  mirLightGreyscale300: Color.rgba(214, 219, 225, 1),
  mirLightUtilityGreen1000: Color.rgba(12, 90, 12, 1),
  mirLightUtilityYellow1000: Color.rgba(62, 55, 5, 1),
  mirLightUtilityRed1000: Color.rgba(90, 12, 12, 1),
  mirLightPrimary1000: Color.rgba(5, 17, 69, 1),
  mirLightPrimary100: Color.rgba(205, 214, 251, 1),
  mirLightAccent11000: Color.rgba(108, 72, 3, 1),
  mirLightAccent1700: Color.rgba(180, 120, 4, 1),
  mirLightAccent1300: Color.rgba(253, 227, 176, 1),
  mirLightAccent1100: Color.rgba(254, 246, 229, 1),
  utilityLightGreyscaleGreyMedium2: Color.rgba(69, 69, 69, 1),
  mirLightGreyscale100White: Color.rgba(255, 255, 255, 1),
  mirLightGreyscale150: Color.rgba(228, 231, 236, 1),
  mirLightGreyscale200White: Color.rgba(255, 255, 255, 1),
  mirLightGreyscale400: Color.rgba(184, 193, 203, 1),
  mirLightGreyscale500: Color.rgba(149, 162, 177, 1),
  mirLightGreyscale600: Color.rgba(122, 124, 146, 1),
  mirLightGreyscale700: Color.rgba(94, 96, 115, 1),
  mirLightGreyscale800: Color.rgba(67, 68, 81, 1),
  mirLightGreyscale900: Color.rgba(39, 40, 48, 1),
  mirLightGreyscale1000: Color.rgba(14, 14, 17, 1),
  mirLightUtilityGreen700: Color.rgba(23, 179, 23, 1),
  mirLightUtilityGreen500: Color.rgba(43, 227, 43, 1),
  mirLightUtilityGreen300: Color.rgba(149, 241, 149, 1),
  mirLightUtilityGreen100: Color.rgba(228, 252, 228, 1),
  mirLightUtilityYellow700: Color.rgba(155, 137, 14, 1),
  mirLightUtilityYellow500: Color.rgba(236, 209, 34, 1),
  mirLightUtilityYellow300: Color.rgba(243, 226, 117, 1),
  mirLightUtilityYellow100: Color.rgba(253, 249, 227, 1),
  mirLightUtilityRed700: Color.rgba(150, 19, 19, 1),
  mirLightUtilityRed500: Color.rgba(227, 43, 43, 1),
  mirLightUtilityRed300: Color.rgba(241, 149, 149, 1),
  mirLightUtilityRed100: Color.rgba(253, 237, 237, 1),
  mirLightGreyscaleTransparent: Color.rgba(255, 255, 255, 1),
  utilityLightGreyscaleGreyMedium3: Color.rgba(69, 69, 69, 1),
  utilityLightGreyscaleAlmostTransparent4: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent5: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent6: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent7: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent8: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent9: Color.rgba(255, 255, 255, 0.00009999999747378752),
  utilityLightGreyscaleAlmostTransparent10: Color.rgba(255, 255, 255, 0.00009999999747378752),
};

const mirDesignSystemShadows = {
  utilityLightArtboardShadow: new DropShadow({
    offset: Point2D.make(0, 3),
    radius: 6,
    color: Color.rgba(0, 0, 0, 0.11999999731779099),
  }),
  utilityLightColorSwatchShadow: new DropShadow({
    offset: Point2D.make(0, 2),
    radius: 5,
    color: Color.rgba(0, 0, 0, 0.2800000011920929),
  }),
  utilityLightColorSwatchShadow1: new DropShadow({
    offset: Point2D.make(0, 2),
    radius: 5,
    color: Color.rgba(0, 0, 0, 0.2800000011920929),
  }),
  utilityLightColorSwatchShadow2: new DropShadow({
    offset: Point2D.make(0, 2),
    radius: 5,
    color: Color.rgba(0, 0, 0, 0.2800000011920929),
  }),
  mirLightShadowLarge: new DropShadow({
    offset: Point2D.make(0, 2),
    radius: 34,
    color: Color.rgba(155, 155, 155, 0.5),
  }),
};

export const mirDesignSystemFonts = {
  Roboto: {
    Medium: Font.fromFile('assets/MirDesignSystem.figma.contents/fonts/Roboto-Medium.ttf'),
    Bold: Font.fromFile('assets/MirDesignSystem.figma.contents/fonts/Roboto-Bold.ttf'),
  },
  Gilroy: {
    SemiBold: Font.fromFile('assets/MirDesignSystem.figma.contents/fonts/Gilroy-SemiBold.otf'),
  },
  Montserrat: {
    Bold: Font.fromFile('assets/MirDesignSystem.figma.contents/fonts/Montserrat-Bold.ttf'),
    Regular: Font.fromFile('assets/MirDesignSystem.figma.contents/fonts/Montserrat-Regular.ttf'),
  },
};

const mirDesignSystemTypography = {
  headingXxLarge: new Typograph({
    letterSpacing: 4.574399871826172,
    fontSize: 76.23999786376953,
    lineHeight: 95.29999542236328,
    color: Color.rgba(43, 43, 43, 1),
    font: mirDesignSystemFonts.Roboto.Medium,
  }),
  headingXLarge: new Typograph({
    letterSpacing: 2.8463999176025387,
    fontSize: 47.439998626708984,
    lineHeight: 59.29999923706055,
    color: Color.rgba(69, 69, 69, 1),
    font: mirDesignSystemFonts.Roboto.Medium,
  }),
  labelMediumBold: new Typograph({
    letterSpacing: 0.6300000000000001,
    fontSize: 18,
    lineHeight: 13,
    color: Color.rgba(255, 255, 255, 1),
    font: mirDesignSystemFonts.Gilroy.SemiBold,
  }),
  headingLarge: new Typograph({
    letterSpacing: 1.759199981689453,
    fontSize: 29.31999969482422,
    lineHeight: 36.650001525878906,
    color: Color.rgba(69, 69, 69, 1),
    font: mirDesignSystemFonts.Roboto.Medium,
  }),
  headingH1: new Typograph({
    letterSpacing: 1,
    fontSize: 60,
    lineHeight: 72,
    color: Color.rgba(39, 40, 48, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  paragraphSmall: new Typograph({
    letterSpacing: 0.5,
    fontSize: 12.5,
    lineHeight: 22,
    color: Color.rgba(39, 40, 48, 1),
    font: new Font({ name: 'OpenSans-Regular' }),
  }),
  paragraphLarge: new Typograph({
    letterSpacing: 0.5,
    fontSize: 29,
    lineHeight: 43.5,
    color: Color.rgba(39, 40, 48, 1),
    font: new Font({ name: 'OpenSans-Regular' }),
  }),
  headingH2: new Typograph({
    letterSpacing: 0,
    fontSize: 37.08281707763672,
    lineHeight: 48.94932174682617,
    color: Color.rgba(39, 40, 48, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  paragraphMedium: new Typograph({
    letterSpacing: 0.5,
    fontSize: 16,
    lineHeight: 28,
    color: Color.rgba(39, 40, 48, 1),
    font: new Font({ name: 'OpenSans-Regular' }),
  }),
  headingH3: new Typograph({
    letterSpacing: 0,
    fontSize: 22.91718101501465,
    lineHeight: 34.375770568847656,
    color: Color.rgba(39, 40, 48, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  headingH4: new Typograph({
    letterSpacing: 0,
    fontSize: 16,
    lineHeight: 24,
    color: Color.rgba(39, 40, 48, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  labelSmallUppercase: new Typograph({
    letterSpacing: 1.2000000000000002,
    fontSize: 12,
    lineHeight: 9,
    color: Color.rgba(69, 69, 69, 1),
    font: mirDesignSystemFonts.Roboto.Medium,
  }),
  labelSingleMediumUppercaseBold: new Typograph({
    letterSpacing: 2,
    fontSize: 16,
    lineHeight: 13,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  labelSingleMediumBold: new Typograph({
    letterSpacing: 1,
    fontSize: 16,
    lineHeight: 13,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  labelSingleMediumRegular: new Typograph({
    letterSpacing: 1,
    fontSize: 16,
    lineHeight: 13,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Montserrat.Regular,
  }),
  labelSingleSmallUppercaseBold: new Typograph({
    letterSpacing: 2,
    fontSize: 11,
    lineHeight: 9,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  labelSingleSmallBold: new Typograph({
    letterSpacing: 1,
    fontSize: 12,
    lineHeight: 9,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Montserrat.Bold,
  }),
  labelSingleSmallRegular: new Typograph({
    letterSpacing: 0.36,
    fontSize: 12,
    lineHeight: 9,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Montserrat.Regular,
  }),
  labelSmall: new Typograph({
    letterSpacing: 0.42000000000000004,
    fontSize: 12,
    lineHeight: 9,
    color: Color.rgba(14, 14, 17, 1),
    font: mirDesignSystemFonts.Roboto.Bold,
  }),
};

export const mirDesignSystemImagesFiles = {
  logoTextReversed: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoTextReversed.png' }),
  logoTextReversed2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoTextReversed@2x.png' }),
  logoTextReversed3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoTextReversed@3x.png' }),
  logoTextReversed4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoTextReversed@4x.png' }),
  logoFramedReversed: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedReversed.png' }),
  logoFramedReversed2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedReversed@2x.png' }),
  logoFramedReversed3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedReversed@3x.png' }),
  logoFramedReversed4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedReversed@4x.png' }),
  artboardSpacingVerticalX6: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX6.png',
  }),
  artboardSpacingVerticalX62x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX6@2x.png',
  }),
  artboardSpacingVerticalX63x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX6@3x.png',
  }),
  artboardSpacingVerticalX64x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX6@4x.png',
  }),
  heading1: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading1.png' }),
  heading12x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading1@2x.png' }),
  heading13x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading1@3x.png' }),
  heading14x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading1@4x.png' }),
  artboardArtboardTitle: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ArtboardArtboardTitle.png' }),
  artboardArtboardTitle2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardArtboardTitle@2x.png',
  }),
  artboardArtboardTitle3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardArtboardTitle@3x.png',
  }),
  artboardArtboardTitle4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardArtboardTitle@4x.png',
  }),
  artboardSpacingVerticalX61: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX61.png',
  }),
  artboardSpacingVerticalX612x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX61@2x.png',
  }),
  artboardSpacingVerticalX613x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX61@3x.png',
  }),
  artboardSpacingVerticalX614x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX61@4x.png',
  }),
  heading2: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading2.png' }),
  heading22x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading2@2x.png' }),
  heading23x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading2@3x.png' }),
  heading24x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading2@4x.png' }),
  artboardSpacingVerticalX5: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX5.png',
  }),
  artboardSpacingVerticalX52x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX5@2x.png',
  }),
  artboardSpacingVerticalX53x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX5@3x.png',
  }),
  artboardSpacingVerticalX54x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX5@4x.png',
  }),
  artboardSectionTitle: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSectionTitle.png' }),
  artboardSectionTitle2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSectionTitle@2x.png' }),
  artboardSectionTitle3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSectionTitle@3x.png' }),
  artboardSectionTitle4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSectionTitle@4x.png' }),
  logoFramedTextReversed: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedTextReversed.png' }),
  logoFramedTextReversed2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedTextReversed@2x.png',
  }),
  logoFramedTextReversed3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedTextReversed@3x.png',
  }),
  logoFramedTextReversed4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/LogoFramedTextReversed@4x.png',
  }),
  artboardSpacingVerticalX51: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX51.png',
  }),
  artboardSpacingVerticalX512x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX51@2x.png',
  }),
  artboardSpacingVerticalX513x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX51@3x.png',
  }),
  artboardSpacingVerticalX514x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX51@4x.png',
  }),
  logoSquareDefault: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoSquareDefault.png' }),
  logoSquareDefault2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoSquareDefault@2x.png' }),
  logoSquareDefault3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoSquareDefault@3x.png' }),
  logoSquareDefault4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LogoSquareDefault@4x.png' }),
  artboardSpacingVerticalX62: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX62.png',
  }),
  artboardSpacingVerticalX622x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX62@2x.png',
  }),
  artboardSpacingVerticalX623x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX62@3x.png',
  }),
  artboardSpacingVerticalX624x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX62@4x.png',
  }),
  colorSwatchX3: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX3.png' }),
  colorSwatchX32x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX3@2x.png' }),
  colorSwatchX33x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX3@3x.png' }),
  colorSwatchX34x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX3@4x.png' }),
  colorSwatchX7: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX7.png' }),
  colorSwatchX72x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX7@2x.png' }),
  colorSwatchX73x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX7@3x.png' }),
  colorSwatchX74x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX7@4x.png' }),
  colorSwatchX31: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX31.png' }),
  colorSwatchX312x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX31@2x.png' }),
  colorSwatchX313x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX31@3x.png' }),
  colorSwatchX314x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX31@4x.png' }),
  colorSwatchX9: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX9.png' }),
  colorSwatchX92x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX9@2x.png' }),
  colorSwatchX93x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX9@3x.png' }),
  colorSwatchX94x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX9@4x.png' }),
  colorSwatchX32: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX32.png' }),
  colorSwatchX322x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX32@2x.png' }),
  colorSwatchX323x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX32@3x.png' }),
  colorSwatchX324x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX32@4x.png' }),
  colorSwatchX8: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX8.png' }),
  colorSwatchX82x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX8@2x.png' }),
  colorSwatchX83x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX8@3x.png' }),
  colorSwatchX84x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ColorSwatchX8@4x.png' }),
  heading3: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading3.png' }),
  heading32x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading3@2x.png' }),
  heading33x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading3@3x.png' }),
  heading34x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Heading3@4x.png' }),
  artboardSpacingVerticalX52: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX52.png',
  }),
  artboardSpacingVerticalX522x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX52@2x.png',
  }),
  artboardSpacingVerticalX523x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX52@3x.png',
  }),
  artboardSpacingVerticalX524x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX52@4x.png',
  }),
  artboardSubSectionTitle: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSubSectionTitle.png',
  }),
  artboardSubSectionTitle2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSubSectionTitle@2x.png',
  }),
  artboardSubSectionTitle3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSubSectionTitle@3x.png',
  }),
  artboardSubSectionTitle4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSubSectionTitle@4x.png',
  }),
  artboardSpacingVerticalX4: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX4.png',
  }),
  artboardSpacingVerticalX42x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX4@2x.png',
  }),
  artboardSpacingVerticalX43x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX4@3x.png',
  }),
  artboardSpacingVerticalX44x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX4@4x.png',
  }),
  headingH1: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH1.png' }),
  headingH12x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH1@2x.png' }),
  headingH13x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH1@3x.png' }),
  headingH14x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH1@4x.png' }),
  paragraphSmall: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphSmall.png' }),
  paragraphSmall2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphSmall@2x.png' }),
  paragraphSmall3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphSmall@3x.png' }),
  paragraphSmall4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphSmall@4x.png' }),
  artboardSpacingVerticalX2: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX2.png',
  }),
  artboardSpacingVerticalX22x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX2@2x.png',
  }),
  artboardSpacingVerticalX23x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX2@3x.png',
  }),
  artboardSpacingVerticalX24x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX2@4x.png',
  }),
  paragraphLarge: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphLarge.png' }),
  paragraphLarge2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphLarge@2x.png' }),
  paragraphLarge3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphLarge@3x.png' }),
  paragraphLarge4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphLarge@4x.png' }),
  headingH2: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH2.png' }),
  headingH22x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH2@2x.png' }),
  headingH23x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH2@3x.png' }),
  headingH24x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH2@4x.png' }),
  paragraphMedium: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphMedium.png' }),
  paragraphMedium2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphMedium@2x.png' }),
  paragraphMedium3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphMedium@3x.png' }),
  paragraphMedium4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphMedium@4x.png' }),
  headingH3: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH3.png' }),
  headingH32x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH3@2x.png' }),
  headingH33x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH3@3x.png' }),
  headingH34x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH3@4x.png' }),
  artboardSpacingVerticalX3: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX3.png',
  }),
  artboardSpacingVerticalX32x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX3@2x.png',
  }),
  artboardSpacingVerticalX33x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX3@3x.png',
  }),
  artboardSpacingVerticalX34x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX3@4x.png',
  }),
  headingH4: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH4.png' }),
  headingH42x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH4@2x.png' }),
  headingH43x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH4@3x.png' }),
  headingH44x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/HeadingH4@4x.png' }),
  paragraphsDemo: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphsDemo.png' }),
  paragraphsDemo2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphsDemo@2x.png' }),
  paragraphsDemo3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphsDemo@3x.png' }),
  paragraphsDemo4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ParagraphsDemo@4x.png' }),
  artboardSpacingVerticalX31: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX31.png',
  }),
  artboardSpacingVerticalX312x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX31@2x.png',
  }),
  artboardSpacingVerticalX313x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX31@3x.png',
  }),
  artboardSpacingVerticalX314x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX31@4x.png',
  }),
  artboardComponentTitle: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ArtboardComponentTitle.png' }),
  artboardComponentTitle2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardComponentTitle@2x.png',
  }),
  artboardComponentTitle3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardComponentTitle@3x.png',
  }),
  artboardComponentTitle4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardComponentTitle@4x.png',
  }),
  labelMediumUppercase: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumUppercase.png' }),
  labelMediumUppercase2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumUppercase@2x.png' }),
  labelMediumUppercase3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumUppercase@3x.png' }),
  labelMediumUppercase4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumUppercase@4x.png' }),
  labelMediumBold: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumBold.png' }),
  labelMediumBold2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumBold@2x.png' }),
  labelMediumBold3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumBold@3x.png' }),
  labelMediumBold4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMediumBold@4x.png' }),
  labelMedium: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMedium.png' }),
  labelMedium2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMedium@2x.png' }),
  labelMedium3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMedium@3x.png' }),
  labelMedium4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelMedium@4x.png' }),
  labelSmallUppercase: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallUppercase.png' }),
  labelSmallUppercase2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallUppercase@2x.png' }),
  labelSmallUppercase3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallUppercase@3x.png' }),
  labelSmallUppercase4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallUppercase@4x.png' }),
  labelSmallBold: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallBold.png' }),
  labelSmallBold2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallBold@2x.png' }),
  labelSmallBold3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallBold@3x.png' }),
  labelSmallBold4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmallBold@4x.png' }),
  labelSmall: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmall.png' }),
  labelSmall2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmall@2x.png' }),
  labelSmall3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmall@3x.png' }),
  labelSmall4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/LabelSmall@4x.png' }),
  pagesHomeDesktop: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeDesktop.png' }),
  pagesHomeDesktop2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeDesktop@2x.png' }),
  pagesHomeDesktop3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeDesktop@3x.png' }),
  pagesHomeDesktop4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeDesktop@4x.png' }),
  pagesEmployeurDesktop: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesEmployeurDesktop.png' }),
  pagesEmployeurDesktop2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/PagesEmployeurDesktop@2x.png',
  }),
  pagesEmployeurDesktop3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/PagesEmployeurDesktop@3x.png',
  }),
  pagesEmployeurDesktop4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/PagesEmployeurDesktop@4x.png',
  }),
  pagesCandidatsDesktop: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesCandidatsDesktop.png' }),
  pagesCandidatsDesktop2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/PagesCandidatsDesktop@2x.png',
  }),
  pagesCandidatsDesktop3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/PagesCandidatsDesktop@3x.png',
  }),
  pagesCandidatsDesktop4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/PagesCandidatsDesktop@4x.png',
  }),
  pagesÀProposDesktop: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesÀProposDesktop.png' }),
  pagesÀProposDesktop2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesÀProposDesktop@2x.png' }),
  pagesÀProposDesktop3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesÀProposDesktop@3x.png' }),
  pagesÀProposDesktop4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesÀProposDesktop@4x.png' }),
  pagesContactDesktop: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesContactDesktop.png' }),
  pagesContactDesktop2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesContactDesktop@2x.png' }),
  pagesContactDesktop3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesContactDesktop@3x.png' }),
  pagesContactDesktop4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesContactDesktop@4x.png' }),
  footer: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Footer.png' }),
  footer2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Footer@2x.png' }),
  footer3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Footer@3x.png' }),
  footer4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/Footer@4x.png' }),
  iconBars: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconBars.png' }),
  iconBars2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconBars@2x.png' }),
  iconBars3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconBars@3x.png' }),
  iconBars4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconBars@4x.png' }),
  topBarMobileDefault: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TopBarMobileDefault.png' }),
  topBarMobileDefault2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TopBarMobileDefault@2x.png' }),
  topBarMobileDefault3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TopBarMobileDefault@3x.png' }),
  topBarMobileDefault4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TopBarMobileDefault@4x.png' }),
  inputsTextInputDefault: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputDefault.png' }),
  inputsTextInputDefault2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputDefault@2x.png',
  }),
  inputsTextInputDefault3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputDefault@3x.png',
  }),
  inputsTextInputDefault4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputDefault@4x.png',
  }),
  inputsTextInputContent: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputContent.png' }),
  inputsTextInputContent2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputContent@2x.png',
  }),
  inputsTextInputContent3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputContent@3x.png',
  }),
  inputsTextInputContent4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputContent@4x.png',
  }),
  inputsTextInputReversedDefault: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedDefault.png',
  }),
  inputsTextInputReversedDefault2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedDefault@2x.png',
  }),
  inputsTextInputReversedDefault3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedDefault@3x.png',
  }),
  inputsTextInputReversedDefault4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedDefault@4x.png',
  }),
  inputsTextInputReversedContent: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedContent.png',
  }),
  inputsTextInputReversedContent2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedContent@2x.png',
  }),
  inputsTextInputReversedContent3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedContent@3x.png',
  }),
  inputsTextInputReversedContent4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedContent@4x.png',
  }),
  illustrationRoundedRectangle: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/IllustrationRoundedRectangle.png',
  }),
  illustrationRoundedRectangle2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/IllustrationRoundedRectangle@2x.png',
  }),
  illustrationRoundedRectangle3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/IllustrationRoundedRectangle@3x.png',
  }),
  illustrationRoundedRectangle4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/IllustrationRoundedRectangle@4x.png',
  }),
  illustrationTools: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationTools.png' }),
  illustrationTools2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationTools@2x.png' }),
  illustrationTools3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationTools@3x.png' }),
  illustrationTools4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationTools@4x.png' }),
  infoTileDefault: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileDefault.png' }),
  infoTileDefault2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileDefault@2x.png' }),
  infoTileDefault3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileDefault@3x.png' }),
  infoTileDefault4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileDefault@4x.png' }),
  infoTileConstruction: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileConstruction.png' }),
  infoTileConstruction2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileConstruction@2x.png' }),
  infoTileConstruction3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileConstruction@3x.png' }),
  infoTileConstruction4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileConstruction@4x.png' }),
  illustrationFactory: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationFactory.png' }),
  illustrationFactory2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationFactory@2x.png' }),
  illustrationFactory3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationFactory@3x.png' }),
  illustrationFactory4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationFactory@4x.png' }),
  infoTileIndustrial: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileIndustrial.png' }),
  infoTileIndustrial2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileIndustrial@2x.png' }),
  infoTileIndustrial3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileIndustrial@3x.png' }),
  infoTileIndustrial4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileIndustrial@4x.png' }),
  infoTileAdmin: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileAdmin.png' }),
  infoTileAdmin2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileAdmin@2x.png' }),
  infoTileAdmin3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileAdmin@3x.png' }),
  infoTileAdmin4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/InfoTileAdmin@4x.png' }),
  iconDot: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconDot.png' }),
  iconDot2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconDot@2x.png' }),
  iconDot3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconDot@3x.png' }),
  iconDot4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconDot@4x.png' }),
  iconCircle: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconCircle.png' }),
  iconCircle2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconCircle@2x.png' }),
  iconCircle3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconCircle@3x.png' }),
  iconCircle4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconCircle@4x.png' }),
  iconArrowRight: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconArrowRight.png' }),
  iconArrowRight2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconArrowRight@2x.png' }),
  iconArrowRight3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconArrowRight@3x.png' }),
  iconArrowRight4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IconArrowRight@4x.png' }),
  buttonMediumSecondaryDefault: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryDefault.png',
  }),
  buttonMediumSecondaryDefault2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryDefault@2x.png',
  }),
  buttonMediumSecondaryDefault3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryDefault@3x.png',
  }),
  buttonMediumSecondaryDefault4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryDefault@4x.png',
  }),
  buttonMediumSecondaryReversed: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryReversed.png',
  }),
  buttonMediumSecondaryReversed2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryReversed@2x.png',
  }),
  buttonMediumSecondaryReversed3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryReversed@3x.png',
  }),
  buttonMediumSecondaryReversed4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryReversed@4x.png',
  }),
  informationSectionPrimary: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionPrimary.png',
  }),
  informationSectionPrimary2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionPrimary@2x.png',
  }),
  informationSectionPrimary3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionPrimary@3x.png',
  }),
  informationSectionPrimary4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionPrimary@4x.png',
  }),
  buttonSmallPrimaryIcon: new File({ src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryIcon.png' }),
  buttonSmallPrimaryIcon2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryIcon@2x.png',
  }),
  buttonSmallPrimaryIcon3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryIcon@3x.png',
  }),
  buttonSmallPrimaryIcon4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryIcon@4x.png',
  }),
  informationSectionSecondary: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionSecondary.png',
  }),
  informationSectionSecondary2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionSecondary@2x.png',
  }),
  informationSectionSecondary3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionSecondary@3x.png',
  }),
  informationSectionSecondary4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionSecondary@4x.png',
  }),
  informationSectionButtonDefault: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionButtonDefault.png',
  }),
  informationSectionButtonDefault2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionButtonDefault@2x.png',
  }),
  informationSectionButtonDefault3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionButtonDefault@3x.png',
  }),
  informationSectionButtonDefault4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/InformationSectionButtonDefault@4x.png',
  }),
  illustrationDesktop: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationDesktop.png' }),
  illustrationDesktop2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationDesktop@2x.png' }),
  illustrationDesktop3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationDesktop@3x.png' }),
  illustrationDesktop4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/IllustrationDesktop@4x.png' }),
  tabSmallDefault: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallDefault.png' }),
  tabSmallDefault2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallDefault@2x.png' }),
  tabSmallDefault3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallDefault@3x.png' }),
  tabSmallDefault4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallDefault@4x.png' }),
  tabSmallSelected: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallSelected.png' }),
  tabSmallSelected2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallSelected@2x.png' }),
  tabSmallSelected3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallSelected@3x.png' }),
  tabSmallSelected4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/TabSmallSelected@4x.png' }),
  buttonSmallPrimaryReversed: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryReversed.png',
  }),
  buttonSmallPrimaryReversed2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryReversed@2x.png',
  }),
  buttonSmallPrimaryReversed3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryReversed@3x.png',
  }),
  buttonSmallPrimaryReversed4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryReversed@4x.png',
  }),
  imageFramesFramedDefault: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ImageFramesFramedDefault.png',
  }),
  imageFramesFramedDefault2x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ImageFramesFramedDefault@2x.png',
  }),
  imageFramesFramedDefault3x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ImageFramesFramedDefault@3x.png',
  }),
  imageFramesFramedDefault4x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ImageFramesFramedDefault@4x.png',
  }),
  artboardSpacingVerticalX7: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX7.png',
  }),
  artboardSpacingVerticalX72x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX7@2x.png',
  }),
  artboardSpacingVerticalX73x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX7@3x.png',
  }),
  artboardSpacingVerticalX74x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX7@4x.png',
  }),
  artboardSpacingHorizontalX1: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingHorizontalX1.png',
  }),
  artboardSpacingHorizontalX12x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingHorizontalX1@2x.png',
  }),
  artboardSpacingHorizontalX13x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingHorizontalX1@3x.png',
  }),
  artboardSpacingHorizontalX14x: new File({
    src: 'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingHorizontalX1@4x.png',
  }),
  pagesHomeMobile: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeMobile.png' }),
  pagesHomeMobile2x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeMobile@2x.png' }),
  pagesHomeMobile3x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeMobile@3x.png' }),
  pagesHomeMobile4x: new File({ src: 'assets/MirDesignSystem.figma.contents/images/PagesHomeMobile@4x.png' }),
};

/**
 * This is provided for backward compatibility, please use `mirDesignSystemImagesFiles` instead.
 * @deprecated
 */
export const mirDesignSystemComponentsFiles = mirDesignSystemImagesFiles;

export const mirDesignSystemImages = {
  logoTextReversed: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/LogoTextReversed.png',
    664.3199462890625,
    228.25624084472656
  ),
  logoFramedReversed: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/LogoFramedReversed.png',
    1038,
    608
  ),
  artboardSpacingVerticalX6: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX6.png',
    1776,
    89
  ),
  heading1: Image.responsive('assets/MirDesignSystem.figma.contents/images/Heading1.png', 1776, 55),
  artboardArtboardTitle: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardArtboardTitle.png',
    1776,
    233
  ),
  artboardSpacingVerticalX61: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX61.png',
    1776,
    89
  ),
  heading2: Image.responsive('assets/MirDesignSystem.figma.contents/images/Heading2.png', 1776, 34),
  artboardSpacingVerticalX5: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX5.png',
    1776,
    55
  ),
  artboardSectionTitle: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSectionTitle.png',
    1776,
    204
  ),
  logoFramedTextReversed: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/LogoFramedTextReversed.png',
    200,
    200
  ),
  artboardSpacingVerticalX51: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX51.png',
    1776,
    55
  ),
  logoSquareDefault: Image.responsive('assets/MirDesignSystem.figma.contents/images/LogoSquareDefault.png', 200, 200),
  artboardSpacingVerticalX62: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX62.png',
    1776,
    89
  ),
  colorSwatchX3: Image.responsive('assets/MirDesignSystem.figma.contents/images/ColorSwatchX3.png', 144, 144),
  colorSwatchX7: Image.responsive('assets/MirDesignSystem.figma.contents/images/ColorSwatchX7.png', 144, 144),
  colorSwatchX31: Image.responsive('assets/MirDesignSystem.figma.contents/images/ColorSwatchX31.png', 377, 377),
  colorSwatchX9: Image.responsive('assets/MirDesignSystem.figma.contents/images/ColorSwatchX9.png', 377, 377),
  colorSwatchX32: Image.responsive('assets/MirDesignSystem.figma.contents/images/ColorSwatchX32.png', 233, 233),
  colorSwatchX8: Image.responsive('assets/MirDesignSystem.figma.contents/images/ColorSwatchX8.png', 233, 233),
  heading3: Image.responsive('assets/MirDesignSystem.figma.contents/images/Heading3.png', 1742, 21),
  artboardSpacingVerticalX52: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX52.png',
    1742,
    55
  ),
  artboardSubSectionTitle: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSubSectionTitle.png',
    1742,
    92
  ),
  artboardSpacingVerticalX4: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX4.png',
    1742,
    34
  ),
  headingH1: Image.responsive('assets/MirDesignSystem.figma.contents/images/HeadingH1.png', 600, 121),
  paragraphSmall: Image.responsive('assets/MirDesignSystem.figma.contents/images/ParagraphSmall.png', 600, 9),
  artboardSpacingVerticalX2: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX2.png',
    600,
    13
  ),
  paragraphLarge: Image.responsive('assets/MirDesignSystem.figma.contents/images/ParagraphLarge.png', 600, 109),
  headingH2: Image.responsive('assets/MirDesignSystem.figma.contents/images/HeadingH2.png', 600, 94),
  paragraphMedium: Image.responsive('assets/MirDesignSystem.figma.contents/images/ParagraphMedium.png', 600, 390),
  headingH3: Image.responsive('assets/MirDesignSystem.figma.contents/images/HeadingH3.png', 600, 21),
  artboardSpacingVerticalX3: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX3.png',
    600,
    21
  ),
  headingH4: Image.responsive('assets/MirDesignSystem.figma.contents/images/HeadingH4.png', 600, 13),
  paragraphsDemo: Image.responsive('assets/MirDesignSystem.figma.contents/images/ParagraphsDemo.png', 521, 566),
  artboardSpacingVerticalX31: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX31.png',
    521.3300170898438,
    21
  ),
  artboardComponentTitle: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardComponentTitle.png',
    521.3300170898438,
    40
  ),
  labelMediumUppercase: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/LabelMediumUppercase.png',
    165,
    13
  ),
  labelMediumBold: Image.responsive('assets/MirDesignSystem.figma.contents/images/LabelMediumBold.png', 165, 13),
  labelMedium: Image.responsive('assets/MirDesignSystem.figma.contents/images/LabelMedium.png', 165, 13),
  labelSmallUppercase: Image.responsive('assets/MirDesignSystem.figma.contents/images/LabelSmallUppercase.png', 165, 9),
  labelSmallBold: Image.responsive('assets/MirDesignSystem.figma.contents/images/LabelSmallBold.png', 165, 9),
  labelSmall: Image.responsive('assets/MirDesignSystem.figma.contents/images/LabelSmall.png', 165, 9),
  pagesHomeDesktop: Image.responsive('assets/MirDesignSystem.figma.contents/images/PagesHomeDesktop.png', 1440, 5622),
  pagesEmployeurDesktop: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/PagesEmployeurDesktop.png',
    1440,
    4876
  ),
  pagesCandidatsDesktop: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/PagesCandidatsDesktop.png',
    1440,
    4876
  ),
  pagesÀProposDesktop: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/PagesÀProposDesktop.png',
    1440,
    5272
  ),
  pagesContactDesktop: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/PagesContactDesktop.png',
    1440,
    2146
  ),
  footer: Image.responsive('assets/MirDesignSystem.figma.contents/images/Footer.png', 375, 740),
  iconBars: Image.responsive('assets/MirDesignSystem.figma.contents/images/IconBars.png', 24, 24),
  topBarMobileDefault: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/TopBarMobileDefault.png',
    375,
    55
  ),
  inputsTextInputDefault: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InputsTextInputDefault.png',
    314,
    34
  ),
  inputsTextInputContent: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InputsTextInputContent.png',
    314,
    34
  ),
  inputsTextInputReversedDefault: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedDefault.png',
    314,
    34
  ),
  inputsTextInputReversedContent: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InputsTextInputReversedContent.png',
    314,
    34
  ),
  illustrationRoundedRectangle: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/IllustrationRoundedRectangle.png',
    248,
    248
  ),
  illustrationTools: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/IllustrationTools.png',
    41.476173400878906,
    41.466949462890625
  ),
  infoTileDefault: Image.responsive('assets/MirDesignSystem.figma.contents/images/InfoTileDefault.png', 248, 248),
  infoTileConstruction: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InfoTileConstruction.png',
    248,
    248
  ),
  illustrationFactory: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/IllustrationFactory.png',
    41.476173400878906,
    41.466949462890625
  ),
  infoTileIndustrial: Image.responsive('assets/MirDesignSystem.figma.contents/images/InfoTileIndustrial.png', 248, 248),
  infoTileAdmin: Image.responsive('assets/MirDesignSystem.figma.contents/images/InfoTileAdmin.png', 248, 248),
  iconDot: Image.responsive('assets/MirDesignSystem.figma.contents/images/IconDot.png', 24, 24),
  iconCircle: Image.responsive('assets/MirDesignSystem.figma.contents/images/IconCircle.png', 24, 24),
  iconArrowRight: Image.responsive('assets/MirDesignSystem.figma.contents/images/IconArrowRight.png', 24, 24),
  buttonMediumSecondaryDefault: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryDefault.png',
    203,
    46
  ),
  buttonMediumSecondaryReversed: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ButtonMediumSecondaryReversed.png',
    203,
    46
  ),
  informationSectionPrimary: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InformationSectionPrimary.png',
    375,
    300
  ),
  buttonSmallPrimaryIcon: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryIcon.png',
    111,
    34
  ),
  informationSectionSecondary: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InformationSectionSecondary.png',
    256,
    192
  ),
  informationSectionButtonDefault: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/InformationSectionButtonDefault.png',
    357,
    322
  ),
  illustrationDesktop: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/IllustrationDesktop.png',
    46.08000183105469,
    44.54405975341797
  ),
  tabSmallDefault: Image.responsive('assets/MirDesignSystem.figma.contents/images/TabSmallDefault.png', 212, 35),
  tabSmallSelected: Image.responsive('assets/MirDesignSystem.figma.contents/images/TabSmallSelected.png', 146, 35),
  buttonSmallPrimaryReversed: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ButtonSmallPrimaryReversed.png',
    118,
    35
  ),
  imageFramesFramedDefault: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ImageFramesFramedDefault.png',
    253.56947326660156,
    254.00001525878906
  ),
  artboardSpacingVerticalX7: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingVerticalX7.png',
    375,
    144
  ),
  artboardSpacingHorizontalX1: Image.responsive(
    'assets/MirDesignSystem.figma.contents/images/ArtboardSpacingHorizontalX1.png',
    9,
    24
  ),
  pagesHomeMobile: Image.responsive('assets/MirDesignSystem.figma.contents/images/PagesHomeMobile.png', 375, 6991),
};

/**
 * This is provided for backward compatibility, please use `mirDesignSystemImages` instead.
 * @deprecated
 */
export const mirDesignSystemComponents = mirDesignSystemImages;

export const mirDesignSystemTokens = {
  colors: mirDesignSystemColors,
  shadows: mirDesignSystemShadows,
  typography: mirDesignSystemTypography,
};
