declare let CORE_LAYOUT_COMPONENT_PATH: string | undefined;
declare let CORE_PROVIDERS_COMPONENT_PATH: string | undefined;

export enum PLUGIN_CONSTANT_NAME {
  CORE_LAYOUT_COMPONENT_PATH = 'CORE_LAYOUT_COMPONENT_PATH',
  CORE_PROVIDERS_COMPONENT_PATH = 'CORE_PROVIDERS_COMPONENT_PATH',
}

export const PLUGIN_CONSTANTS = {
  [PLUGIN_CONSTANT_NAME.CORE_LAYOUT_COMPONENT_PATH]: CORE_LAYOUT_COMPONENT_PATH,
  [PLUGIN_CONSTANT_NAME.CORE_PROVIDERS_COMPONENT_PATH]: CORE_PROVIDERS_COMPONENT_PATH,
};
