export enum PROJECT_PAGE_TYPE {
  HOME = 'HOME',
  CLINIC = 'CLINIC',
  VASECTOMY_FORM = 'VASECTOMY_FORM',
  FORM = 'FORM',
  PILOT_EXAM = 'PILOT_EXAM',
  CONTACT = 'CONTACT',
}

export enum PROJECT_SECTION_TYPE {
  BANNER = 'BANNER',
  MESSAGE = 'MESSAGE',
  TILE_LINKS = 'TILE_LINKS',
  CLINIC_PREVIEW = 'CLINIC_PREVIEW',
  CONTACT_PREVIEW = 'CONTACT_PREVIEW',
  CLINIC_MISSION = 'CLINIC_MISSION',
  CLINIC_DR_PROFILE = 'CLINIC_DR_PROFILE',
  VASECTOMY_STEPS = 'VASECTOMY_STEPS',
  VASECTOMY_INFO = 'VASECTOMY_INFO',
  VASECTOMY_INFO_BEFORE = 'VASECTOMY_INFO_BEFORE',
  VASECTOMY_INFO_COST = 'VASECTOMY_INFO_COST',
  VASECTOMY_INFO_AFTER = 'VASECTOMY_INFO_AFTER',
  VASECTOMY_FORM_LINK = 'VASECTOMY_FORM_LINK',
  VASECTOMY_FORM_VIDEO = 'VASECTOMY_FORM_VIDEO',
  VASECTOMY_FORM_FORM = 'VASECTOMY_FORM_FORM',
  PILOT_EXAM_INFO = 'PILOT_EXAM_INFO',
  PILOT_EXAM_SERVICE = 'PILOT_EXAM_SERVICE',
  PILOT_EXAM_DR_PROFILE = 'PILOT_EXAM_DR_PROFILE',
  CONTACT_CONTACT = 'CONTACT_CONTACT',
}

export enum PROJECT_CONTENT_TYPE {
  STEP = 'STEP',
  COST_ITEM = 'COST_ITEM',
  THEMATIC = 'THEMATIC',
  SERVICE = 'SERVICE',
  SERVICE_CATEGORY = 'SERVICE_CATEGORY',
  TECHNOLOGY = 'TECHNOLOGY',
}

export enum PROJECT_FIELD {
  STEP = 'step',
  COST_ITEM = 'costItem',
  THEMATIC = 'thematic',
  SERVICE = 'service',
  SERVICE_CATEGORY = 'serviceCategory',
  TECHNOLOGY = 'technology',
  SUMMARY = 'summary',
}

export enum PROJECT_SERVICE_CATEGORY {}
