export enum COMMON_VARIANT {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  TERTIARY = 'TERTIARY',
}

export enum COMMON_STYLE_VARIANT {
  NORMAL = 'NORMAL',
  REVERSED = 'REVERSED',
}

export enum CAROUSEL_STYLE {
  CAROUSEL_VERTICAL = 'CAROUSEL_VERTICAL',
  CAROUSEL_HORIZONTAL = 'CAROUSEL_HORIZONTAL',
}

export enum COMMON_SIZE {
  X_SMALL = 'X_SMALL',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
  X_LARGE = 'X_LARGE',
}
