export enum COMMON_VARIANT {
  PRIMARY_NORMAL = 'PRIMARY_NORMAL',
  PRIMARY_REVERSED = 'PRIMARY_REVERSED',
  SECONDARY_NORMAL = 'SECONDARY_NORMAL',
  TERTIARY_NORMAL = 'TERTIARY_NORMAL',
  SECONDARY_REVERSED = 'SECONDARY_REVERSED',
  TERTIARY_REVERSED = 'TERTIARY_REVERSED',
}

export enum COMMON_VARIANT_LAYOUT {
  PRIMARY_NORMAL = 'PRIMARY_NORMAL',
  PRIMARY_REVERSED = 'PRIMARY_REVERSED',
  SECONDARY_NORMAL = 'SECONDARY_NORMAL',
  TERTIARY_NORMAL = 'TERTIARY_NORMAL',
  SECONDARY_REVERSED = 'SECONDARY_REVERSED',
  TERTIARY_REVERSED = 'TERTIARY_REVERSED',
}

export enum CAROUSEL_STYLE {
  CAROUSEL_VERTICAL = 'CAROUSEL_VERTICAL',
  CAROUSEL_HORIZONTAL = 'CAROUSEL_HORIZONTAL',
}

export enum COMMON_SIZE {
  X_SMALL = 'X_SMALL',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
  X_LARGE = 'X_LARGE',
}
