import { ICON } from '@newrade/core-design-system';
import {
  IoAddCircleOutline,
  IoAddOutline,
  IoAppsOutline,
  IoArrowBackCircleOutline,
  IoArrowBackOutline,
  IoArrowDownCircleOutline,
  IoArrowDownOutline,
  IoArrowForwardCircleOutline,
  IoArrowForwardOutline,
  IoArrowUpCircleOutline,
  IoArrowUpOutline,
  IoCalendarOutline,
  IoCallOutline,
  IoCaretBackCircleOutline,
  IoCaretBackOutline,
  IoCaretDownCircleOutline,
  IoCaretDownOutline,
  IoCaretForwardCircleOutline,
  IoCaretForwardOutline,
  IoCaretUpCircleOutline,
  IoCaretUpOutline,
  IoCheckboxOutline,
  IoCheckmarkCircleOutline,
  IoCheckmarkOutline,
  IoChevronBackCircleOutline,
  IoChevronBackOutline,
  IoChevronDownCircleOutline,
  IoChevronDownOutline,
  IoChevronForwardCircleOutline,
  IoChevronForwardOutline,
  IoChevronUpCircleOutline,
  IoChevronUpOutline,
  IoCloseCircleOutline,
  IoCloseOutline,
  IoCopyOutline,
  IoDocumentOutline,
  IoDownloadOutline,
  IoDuplicateOutline,
  IoEllipsisVertical,
  IoExitOutline,
  IoHomeOutline,
  IoLayersOutline,
  IoLocationOutline,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoLogoTwitter,
  IoLogoYoutube,
  IoMailOutline,
  IoMenuOutline,
  IoOpenOutline,
  IoPersonCircleOutline,
  IoPrintOutline,
  IoRadioButtonOffOutline,
  IoRadioButtonOnOutline,
  IoRemoveCircleOutline,
  IoRemoveOutline,
  IoSearchOutline,
} from 'react-icons/io5';
import { IconComponents } from '../icons/icons-provider';

export const ionicons5Kit: IconComponents<ICON> = {
  [ICON.IO_ARROW_UP]: IoArrowUpOutline,
  [ICON.IO_ARROW_DOWN]: IoArrowDownOutline,
  [ICON.IO_ARROW_LEFT]: IoArrowBackOutline,
  [ICON.IO_ARROW_RIGHT]: IoArrowForwardOutline,
  [ICON.IO_CHEVRON_UP]: IoChevronUpOutline,
  [ICON.IO_CHEVRON_DOWN]: IoChevronDownOutline,
  [ICON.IO_CHEVRON_LEFT]: IoChevronBackOutline,
  [ICON.IO_CHEVRON_RIGHT]: IoChevronForwardOutline,
  [ICON.IO_CARET_UP]: IoCaretUpOutline,
  [ICON.IO_CARET_DOWN]: IoCaretDownOutline,
  [ICON.IO_CARET_LEFT]: IoCaretBackOutline,
  [ICON.IO_CARET_RIGHT]: IoCaretForwardOutline,
  [ICON.IO_MENU]: IoMenuOutline,
  [ICON.IO_ELLIPSIS_VERTICAL]: IoEllipsisVertical,
  [ICON.IO_APPS]: IoAppsOutline,
  [ICON.IO_ADD]: IoAddOutline,
  [ICON.IO_REMOVE]: IoRemoveOutline,
  [ICON.IO_CLOSE]: IoCloseOutline,
  [ICON.IO_SEARCH]: IoSearchOutline,
  [ICON.IO_CALENDAR]: IoCalendarOutline,
  [ICON.IO_CALL]: IoCallOutline,
  [ICON.IO_PRINT]: IoPrintOutline,
  [ICON.IO_OPEN]: IoOpenOutline,
  [ICON.IO_EXIT]: IoExitOutline,
  [ICON.IO_LOCATION]: IoLocationOutline,
  [ICON.IO_MAIL]: IoMailOutline,
  [ICON.IO_HOME]: IoHomeOutline,
  [ICON.IO_DOWNLOAD]: IoDownloadOutline,
  [ICON.IO_COPY]: IoCopyOutline,
  [ICON.IO_DUPLICATE]: IoDuplicateOutline,
  [ICON.IO_DOCUMENT]: IoDocumentOutline,
  [ICON.IO_LAYERS]: IoLayersOutline,
  [ICON.IO_CHECK]: IoCheckmarkOutline,
  [ICON.IO_CHECKMARK_CIRCLE]: IoCheckmarkCircleOutline,
  [ICON.IO_CHECKBOX]: IoCheckboxOutline,
  [ICON.IO_ARROW_UP_CIRCLE]: IoArrowUpCircleOutline,
  [ICON.IO_ARROW_DOWN_CIRCLE]: IoArrowDownCircleOutline,
  [ICON.IO_ARROW_LEFT_CIRCLE]: IoArrowBackCircleOutline,
  [ICON.IO_ARROW_RIGHT_CIRCLE]: IoArrowForwardCircleOutline,
  [ICON.IO_CHEVRON_UP_CIRCLE]: IoChevronUpCircleOutline,
  [ICON.IO_CHEVRON_DOWN_CIRCLE]: IoChevronDownCircleOutline,
  [ICON.IO_CHEVRON_LEFT_CIRCLE]: IoChevronBackCircleOutline,
  [ICON.IO_CHEVRON_RIGHT_CIRCLE]: IoChevronForwardCircleOutline,
  [ICON.IO_CARET_UP_CIRCLE]: IoCaretUpCircleOutline,
  [ICON.IO_CARET_DOWN_CIRCLE]: IoCaretDownCircleOutline,
  [ICON.IO_CARET_LEFT_CIRCLE]: IoCaretBackCircleOutline,
  [ICON.IO_CARET_RIGHT_CIRCLE]: IoCaretForwardCircleOutline,
  [ICON.IO_ADD_CIRCLE]: IoAddCircleOutline,
  [ICON.IO_REMOVE_CIRCLE]: IoRemoveCircleOutline,
  [ICON.IO_CLOSE_CIRCLE]: IoCloseCircleOutline,
  [ICON.IO_PERSON_CIRCLE]: IoPersonCircleOutline,
  [ICON.IO_RADIO_ON]: IoRadioButtonOnOutline,
  [ICON.IO_RADIO_OFF]: IoRadioButtonOffOutline,
  [ICON.IO_LOGO_TWITTER]: IoLogoTwitter,
  [ICON.IO_LOGO_FACEBOOK]: IoLogoFacebook,
  [ICON.IO_LOGO_INSTAGRAM]: IoLogoInstagram,
  [ICON.IO_LOGO_LINKEDIN]: IoLogoLinkedin,
  [ICON.IO_LOGO_YOUTUBE]: IoLogoYoutube,
};
