import { ICON } from '@newrade/core-design-system';
import {
  IoAddCircle,
  IoAddOutline,
  IoAppsOutline,
  IoArrowBackOutline,
  IoArrowDownOutline,
  IoArrowForwardOutline,
  IoArrowUpOutline,
  IoCalendarOutline,
  IoCaretBackOutline,
  IoCaretDownOutline,
  IoCaretForwardOutline,
  IoCaretUpOutline,
  IoCheckboxOutline,
  IoCheckmarkCircleOutline,
  IoCheckmarkOutline,
  IoChevronBackOutline,
  IoChevronDownOutline,
  IoChevronForwardOutline,
  IoChevronUpOutline,
  IoCloseOutline,
  IoCopyOutline,
  IoDocumentOutline,
  IoDownloadOutline,
  IoDuplicateOutline,
  IoEllipsisVertical,
  IoExitOutline,
  IoLayersOutline,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoLogoTwitter,
  IoLogoYoutube,
  IoMenuOutline,
  IoOpenOutline,
  IoRadioButtonOffOutline,
  IoRadioButtonOnOutline,
  IoRemoveOutline,
  IoSearchOutline,
} from 'react-icons/io5';
import { IconComponents } from '../icons/icons-provider';
import { newradeIconsKit } from './newrade-icons';

export const ionicons5Kit: IconComponents<ICON> = {
  [ICON.ARROW_UP]: IoArrowUpOutline,
  [ICON.ARROW_DOWN]: IoArrowDownOutline,
  [ICON.ARROW_LEFT]: IoArrowBackOutline,
  [ICON.ARROW_RIGHT]: IoArrowForwardOutline,
  [ICON.CHEVRON_UP]: IoChevronUpOutline,
  [ICON.CHEVRON_DOWN]: IoChevronDownOutline,
  [ICON.CHEVRON_LEFT]: IoChevronBackOutline,
  [ICON.CHEVRON_RIGHT]: IoChevronForwardOutline,
  [ICON.CARET_UP]: IoCaretUpOutline,
  [ICON.CARET_DOWN]: IoCaretDownOutline,
  [ICON.CARET_LEFT]: IoCaretBackOutline,
  [ICON.CARET_RIGHT]: IoCaretForwardOutline,
  [ICON.MENU]: IoMenuOutline,
  [ICON.ELLIPSIS_VERTICAL]: IoEllipsisVertical,
  [ICON.APPS]: IoAppsOutline,
  [ICON.ADD]: IoAddOutline,
  [ICON.REMOVE]: IoRemoveOutline,
  [ICON.CLOSE]: IoCloseOutline,
  [ICON.SEARCH]: IoSearchOutline,
  [ICON.CALENDAR]: IoCalendarOutline,
  [ICON.OPEN]: IoOpenOutline,
  [ICON.EXIT]: IoExitOutline,
  [ICON.DOWNLOAD]: IoDownloadOutline,
  [ICON.COPY]: IoCopyOutline,
  [ICON.DUPLICATE]: IoDuplicateOutline,
  [ICON.DOCUMENT]: IoDocumentOutline,
  [ICON.LAYERS]: IoLayersOutline,
  [ICON.CHECK]: IoCheckmarkOutline,
  [ICON.CHECKMARK_CIRCLE]: IoCheckmarkCircleOutline,
  [ICON.CHECKBOX]: IoCheckboxOutline,
  [ICON.CIRCLE]: IoAddCircle,
  [ICON.RADIO_ON]: IoRadioButtonOnOutline,
  [ICON.RADIO_OFF]: IoRadioButtonOffOutline,
  [ICON.LOGO_TWITTER]: IoLogoTwitter,
  [ICON.LOGO_FACEBOOK]: IoLogoFacebook,
  [ICON.LOGO_INSTAGRAM]: IoLogoInstagram,
  [ICON.LOGO_LINKEDIN]: IoLogoLinkedin,
  [ICON.LOGO_YOUTUBE]: IoLogoYoutube,
  ...newradeIconsKit,
};
