import { StatsOptions } from 'webpack';

/**
 * @description Webpack Stats Configuration
 * @see https://webpack.js.org/configuration/stats/
 */
export const stats: { [key in 'debug' | 'dev' | 'prod']: StatsOptions } = {
  debug: {
    all: false,
    colors: false,
    assets: true,
    children: true,
    chunks: true,
    chunkModules: true,
    chunkGroups: true,
    assetsSort: 'size',
    chunksSort: 'size',
    entrypoints: true,
    env: true,
    publicPath: true,
    errors: true,
    errorDetails: true,
    modules: true,
    moduleTrace: false,
    performance: true,
    timings: true,
    warnings: true,
    version: true,
    hash: false,
    optimizationBailout: true,
    logging: 'verbose',
  },
  dev: {
    all: false,
    colors: true,
    assets: false,
    children: true,
    chunks: false,
    chunkModules: false,
    chunkGroups: false,
    chunksSort: 'size',
    entrypoints: false,
    env: true,
    publicPath: false,
    errors: true,
    errorDetails: true,
    modules: false,
    moduleTrace: false,
    performance: true,
    timings: true,
    warnings: true,
    version: false,
    hash: false,
    optimizationBailout: true, // display bailout reasons
  },
  prod: {
    all: false,
    colors: false,
    assets: true,
    children: true,
    chunks: true,
    chunkModules: true,
    chunkGroups: true,
    assetsSort: 'size',
    chunksSort: 'size',
    entrypoints: true,
    env: true,
    publicPath: true,
    errors: true,
    errorDetails: true,
    modules: true,
    moduleTrace: false,
    performance: true,
    timings: true,
    warnings: true,
    version: true,
    hash: false,
    optimizationBailout: false,
    logging: 'warn',
  },
};
