/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit the source file at `./config/gatsby-node.ts`
 */
// module.exports = require('./gatsby/config/gatsby-node');

module.exports = {
  /* Your site config here */
  // plugins: [],
};
