export * from './blockquote.js';
export * from './details.js';
export * from './heading.js';
export * from './hr.js';
export * from './label.js';
export * from './link.js';
export * from './paragraph.js';
export * from './summary.js';
export * from './text-common.props.js';
