export enum PROJECT_PAGE_TYPE {
  HOME = 'HOME',
  A_PROPS = 'A_PROPS',
  SERVICES = 'SERVICES',
  SERVICES_SCENARISATION_VIDEO = 'SERVICES_SCENARISATION_VIDEO',
  SERVICES_CONCEPTION_REDACTION = 'SERVICES_CONCEPTION_REDACTION',
  SERVICES_NARRATION = 'SERVICES_NARRATION',
  PORTFOLIO = 'PORTFOLIO',
  CLIENT = 'CLIENT',
  CONTACT = 'CONTACT',
}

export enum PROJECT_SECTION_TYPE {
  BANNER = 'BANNER',
  VALENTINE_PREVIEW = 'VALENTINE_PREVIEW',
  VALENTINE_STEPS = 'VALENTINE_STEPS',
  VALENTINE_CONTENT = 'VALENTINE_INFO',
  VALENTINE_INFO = 'VALENTINE_INFO',
  VALENTINE_SERVICE_TILE = 'VALENTINE_SERVICE_TILE',
  CLIENT_PREVIEW = 'CLIENT_PREVIEW',
  CONTACT_PREVIEW = 'CONTACT_PREVIEW',
  CONTACT_CONTACT = 'CONTACT_CONTACT',
}

export enum PROJECT_CONTENT_TYPE {
  STEP = 'STEP',
}

export enum PROJECT_FIELD {
  STEP = 'step',
}
