export enum PROJECT_PAGE_TYPE {
  HOME = 'HOME',
  A_PROPS = 'A_PROPS',
  SERVICES = 'SERVICES',
  SCENARISATION_VIDEO = 'SCENARISATION_VIDEO',
  CONCEPTION_REDACTION = 'CONCEPTION_REDACTION',
  NARRATION = 'NARRATION',
  PORTFOLIO = 'PILOT_EXAM',
  CONTACT = 'CONTACT',
}

export enum PROJECT_SECTION_TYPE {
  BANNER = 'BANNER',
  VALENTINE_PREVIEW = 'CLINIC_PREVIEW',
  CONTACT_PREVIEW = 'CONTACT_PREVIEW',
  VALENTINE_STEPS = 'VALENTINE_STEPS',
  VALENTINE_INFO = 'VALENTINE_INFO',
  CONTACT_CONTACT = 'CONTACT_CONTACT',
}

export enum PROJECT_CONTENT_TYPE {
  STEP = 'STEP',
}

export enum PROJECT_FIELD {
  STEP = 'step',
}
