export enum PROJECT_PAGE_TYPE {
  HOME,
  CLINIC,
  VASECTOMY_FORM,
  FORM,
  PILOT_EXAM,
  CONTACT,
}

export enum PROJECT_SECTION_TYPE {
  BANNER = 'BANNER',
  CONTACT_CONTACT = 'CONTACT_CONTACT',
}

export enum PROJECT_CONTENT_TYPE {
  STEP = 'STEP',
  COST_ITEM = 'COST_ITEM',
}
