import {
  BoxV2,
  BoxV3,
  Center,
  Cluster,
  Code,
  CodeBlock,
  CodeHighlight,
  Details,
  Grid,
  Heading,
  ListItem,
  ListItems,
  mdxComponents,
  Paragraph,
  Stack,
  Summary,
  Switcher,
} from '@newrade/core-react-ui';
import { Placeholder } from './utils/placeholder';
import { PlaceholderMarkdown } from './utils/placeholder-markdown';
import { Variant } from '@newrade/core-design-system';
import {
  BlockMarkdown,
  SectionSwitcher,
  SectionBase,
  SectionDivider,
  SectionBaseLayout,
  SectionPadding,
} from '@newrade/core-gatsby-ui/src';

export const designSystemMdxComponents = {
  ...mdxComponents,
  BoxV2: BoxV2,
  BoxV3: BoxV3,
  Center: Center,
  Code: Code,
  Cluster: Cluster,
  Details: Details,
  ListItem: ListItem,
  ListItems: ListItems,
  Grid: Grid,
  BlockMarkdown: BlockMarkdown,
  Heading: Heading,
  Paragraph: Paragraph,
  Placeholder: Placeholder,
  PlaceholderMarkdown: PlaceholderMarkdown,
  SectionSwitcher: SectionSwitcher,
  Section: SectionBase,
  Stack: Stack,
  Summary: Summary,
  Switcher: Switcher,
  SectionDivider: SectionDivider,
  SectionLayout: SectionBaseLayout,
  SectionPadding: SectionPadding,
  Variant: Variant,
  CodeHighlight: CodeHighlight,
  CodeBlock: CodeBlock,
};
