import {
  createTextStyle,
  Headings,
  HEADING_LEVEL,
  LABEL,
  Labels,
  PARAGRAPH,
  Paragraphs,
  Typography,
  VIEWPORT,
} from 'core-design-system';
import { fonts } from './fonts';
import { sizing, BASE_FONT_SIZE } from './sizing';

const mobileHeadings: Headings = {
  [HEADING_LEVEL.H1]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X5,
    lineGap: 28,
  }),
  [HEADING_LEVEL.H2]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X4,
    lineGap: 19,
  }),
  [HEADING_LEVEL.H3]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X3,
    lineGap: 14,
  }),
  [HEADING_LEVEL.H4]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 10,
  }),
};

const mobileParagraphs: Paragraphs = {
  [PARAGRAPH.LARGE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '1%',
    capHeight: sizing.sizingSteps.MOBILE.X3,
    lineGap: 19,
  }),
  [PARAGRAPH.MEDIUM]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '2%',
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 16,
  }),
  [PARAGRAPH.SMALL]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '3%',
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 12,
  }),
  [PARAGRAPH.X_SMALL]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '3%',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
};

const mobileLabels: Labels = {
  [LABEL.MEDIUM_BOLD_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    letterSpacing: '12%',
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.MEDIUM_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    letterSpacing: '12%',
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.MEDIUM_BOLD]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    letterSpacing: '6%',
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.MEDIUM_REGULAR]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    letterSpacing: '6%',
    fontFamily: 'Montserrat',
    fontWeight: 400,
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.SMALL_BOLD_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    letterSpacing: '12%',
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.SMALL_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    letterSpacing: '12%',
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.SMALL_BOLD]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.SMALL_REGULAR]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    letterSpacing: '6%',
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_BOLD_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    letterSpacing: '12%',
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    letterSpacing: '12%',
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_BOLD]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    letterSpacing: '6%',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_REGULAR]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    letterSpacing: '6%',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
};

const desktopHeadings: Headings = {
  [HEADING_LEVEL.H1]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.DESKTOP.X5,
    lineGap: 46,
  }),
  [HEADING_LEVEL.H2]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.DESKTOP.X4,
    lineGap: 30,
  }),
  [HEADING_LEVEL.H3]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.DESKTOP.X3,
    lineGap: 10,
  }),
  [HEADING_LEVEL.H4]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 18,
  }),
};

const desktopParagraphs: Paragraphs = {
  [PARAGRAPH.LARGE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '1%',
    capHeight: sizing.sizingSteps.DESKTOP.X3,
    lineGap: 25,
  }),
  [PARAGRAPH.MEDIUM]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '2%',
    capHeight: sizing.sizingSteps.DESKTOP.X2,
    lineGap: 14,
  }),
  [PARAGRAPH.SMALL]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '3%',
    capHeight: sizing.sizingSteps.DESKTOP.X1,
    lineGap: 11,
  }),
  [PARAGRAPH.X_SMALL]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS_ALTERNATE,
    fontFamily: 'Open Sans',
    fontWeight: 400,
    letterSpacing: '3%',
    capHeight: sizing.sizingSteps.DESKTOP.X0,
    lineGap: 8,
  }),
};

const desktopLabels: Labels = {
  [LABEL.MEDIUM_BOLD_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.MEDIUM_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.MEDIUM_BOLD]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.MEDIUM_REGULAR]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    capHeight: sizing.sizingSteps.MOBILE.X2,
    lineGap: 12,
  }),
  [LABEL.SMALL_BOLD_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.SMALL_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.SMALL_BOLD]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.SMALL_REGULAR]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    capHeight: sizing.sizingSteps.MOBILE.X1,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_BOLD_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_UPPERCASE]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    textTransform: 'uppercase',
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_BOLD]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 700,
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
  [LABEL.X_SMALL_REGULAR]: createTextStyle({
    baseFontSize: BASE_FONT_SIZE,
    font: fonts.SANS,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    capHeight: sizing.sizingSteps.MOBILE.X0,
    lineGap: 8,
  }),
};

export const typography: Typography = {
  fonts,
  headings: {
    [VIEWPORT.MOBILE]: mobileHeadings,
    [VIEWPORT.TABLET]: desktopHeadings,
    [VIEWPORT.DESKTOP]: desktopHeadings,
  },
  paragraphs: {
    [VIEWPORT.MOBILE]: mobileParagraphs,
    [VIEWPORT.TABLET]: desktopParagraphs,
    [VIEWPORT.DESKTOP]: desktopParagraphs,
  },
  labels: {
    [VIEWPORT.MOBILE]: mobileLabels,
    [VIEWPORT.TABLET]: desktopLabels,
    [VIEWPORT.DESKTOP]: desktopLabels,
  },
};
