import fs from 'fs';
import path from 'path';

const projectJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../../package.json'), 'utf-8')
);

export function createExportFile(options: { path: string; data?: string }) {
  const fileData = options.data
    ? options.data
    : `/** auto-generated by ${projectJson.name} v${projectJson.version} - ${new Date()
        .toLocaleDateString('en', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
        })
        .split('/')
        .join('-')} */\n`;

  fs.writeFileSync(path.join(options.path), fileData);
}

export function createExportJSONFile(options: { path: string; data?: string }) {
  // no comments are allowed in JSON
  fs.writeFileSync(path.join(options.path), options.data ? options.data : ``);
}
